---
###############################################################################
# Postfix MTA Virtual Mail
###############################################################################
# Postfix attempts to be fast, easy to administer, and secure. The outside has
# a definite Sendmail-ish flavor, but the inside is completely different.
#
# Configures virtual mail domains, aliases, and maps.
#
# Domain Mapping:
#   Use {DOMAIN} OK in domain mapping file for valid texthash.
#
# User/Alias/Mailbox Mapping:
#   {MAP} {DOMAIN}/{USER}/ must end with trailing slash, else mbox format is
#   assumed.
#
# Postfix/Postmap:
#   Postfix in-memory lookup tables (PCRE, CIDR, REGEX, TEXTHASH) do not
#   require 'postmap', but may require 'postfix reload' on long running
#   commmands like trivial-rewrite.
#
#   Using berkley DB (HASH, CDB, DBM, LMDB, SDBM) requires postmap to be run
#   but does not require 'postfix reload' for changes to be recognized.
#
#   As this is a small postfix site (< 30 mails per second, 500k mails/day ish)
#   we prefer in-memory lookup tables as the data is trivially small, and
#   changes will be applied through this role, which forces a reload anyways.
#
# Args:
#   mail_domains: list of strings containing hosted mail domains. The first
#      domain listed is the primary domain. A primary domain is the default
#      domain mail is sent from when a sender is not fully specified.
#   mail_users: list of dicts containing virtual users.
#       {
#         user: '{USER}@{DOMAIN}',
#         pass: '{PASS OR HASH}',
#         uid: '{OPTIONAL user ID},
#         gid: '{OPTIONAL group ID},
#         gecos: '{OPTIONAL gecos field}'
#         home: '{OPTIONAL home directory}'
#         shell: '{OPTIONAL user shell}'
#         extra: '{OPTIONAL extra parameters: mail plugins, ip restrictions}'
#       }
#   mail_box_mappings: list of dicts mapping additional mailboxes to existing
#       users.
#       {
#         'map': {FQDN EMAIL},
#         'to': {VALID USER FROM mail_users}
#       }
#   mail_aliases: list of dicts mapping aliases to existing users.
#       {
#         'map': {FQDN EMAIL},
#         'to': {VALID USER FROM mail_users}
#       }
#   mail_purge_install: boolean true to purge custom files before config.
#
# Reference:
# * http://www.postfix.org/
# * https://workaround.org/ispmail
# * http://www.postfix.org/DATABASE_README.html
# * http://www.postfix.org/VIRTUAL_README.html#virtual_mailbox
# * http://www.postfix.org/postconf.5.html#virtual_mailbox_domains
# * http://www.postfix.org/postconf.5.html#virtual_mailbox_maps
# * http://www.postfix.org/postconf.5.html#virtual_alias_maps
# * https://blog.tinned-software.net/setup-postfix-for-multiple-domains/

- name: 'postfix virtual | purge existing configuration data'
  ansible.builtin.file:
    path:  '/etc/postfix/virtual'
    state: 'absent'
  loop:
  when: mail_purge_install

- name: 'postfix virtual | create virtual directory'
  ansible.builtin.file:
    path:  '/etc/postfix/virtual'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode:  0755

- name: 'postfix virtual | add virtual domains'
  ansible.builtin.template:
    src:   'postfix/virtual/mailbox_domains.j2'
    dest:  '/etc/postfix/virtual/mailbox_domains'
    owner: 'root'
    group: 'root'
    mode:  0644
  notify: 'reload postfix'

- name: 'postfix virtual | add virtual users, mailbox mappings'
  ansible.builtin.template:
    src:   'postfix/virtual/mailbox_maps.j2'
    dest:  '/etc/postfix/virtual/mailbox_maps'
    owner: 'root'
    group: 'root'
    mode:  0644
  notify: 'reload postfix'

# Per RFC 821, 2142 add abuse@, postermaster@ if not defined.
- name: 'postfix virtual | add virtual aliases'
  ansible.builtin.template:
    src:   'postfix/virtual/alias_maps.j2'
    dest:  '/etc/postfix/virtual/alias_maps'
    owner: 'root'
    group: 'root'
    mode:  0644
  vars:
    no_abuse_defined:      '{{ not __abuse_defined|bool }}'
    no_postmaster_defined: '{{ not __postmaster_defined|bool }}'
    no_catch_all_defined:  '{{ not __catch_all_defined|bool }}'
  notify: reload postfix
