---
###############################################################################
# Dovecot Virtual User (/etc/dovecot/userdb) Configuration
###############################################################################
# Dovecot is an open source IMAP and POP3 email server for Linux/UNIX-like
# systems, written with security primarily in mind. Dovecot is an excellent
# choice for both small and large installations. It’s fast, simple to set up,
# requires no special administration and it uses very little memory.
#
# Use /etc/dovecot/userdb for virtual users, with full passwd-like support.
#     user:password:uid:gid:(gecos):home:(shell):extra_fields
#
# Create user manually with:
#
#   doveadm pw -s ARGON2ID
#
# Args:
#   user: dict for virtual email user.
#       {
#         user: '{USER}@{DOMAIN}',
#         pass: '{PASS OR HASH}',
#         uid: '{OPTIONAL user ID},
#         gid: '{OPTIONAL group ID},
#         gecos: '{OPTIONAL gecos field}'
#         home: '{OPTIONAL home directory}'
#         shell: '{OPTIONAL user shell}'
#         extra: '{OPTIONAL extra parameters: mail plugins, ip restrictions}'
#       }
#   __log_int: integer translation of user requested logging level (using map).
#
# Disable change notifications -- truncated userdb (to ensure remove users are
# deleted) will always caused these to report 'changed' states.
#
# Reference:
# * https://www.dovecot.org/
# * https://doc.dovecot.org/configuration_manual/authentication/passwd_file/
# * https://doc.dovecot.org/configuration_manual/authentication/password_schemes/#authentication-password-schemes

- name: 'dovecot userdb | encrypting {{ user.user }} user password using ARGON2ID'
  ansible.builtin.command: 'doveadm pw {% if __log_int|int > 3 %}-D{% endif %} -s ARGON2ID -p "{{ user.pass }}"'
  register: _mail_dovecot_user_hash
  changed_when: false
  when: '"{ARGON2ID}" not in user.pass'
  no_log: true # plaintext password is possible

- name: 'dovecot userdb | update virtual user {{ user.user }}'
  ansible.builtin.lineinfile:
    path:   '/etc/dovecot/userdb'
    regexp: '^#?\s*{{ user.user }}'
    line:   '{{ user.user }}:{% if _mail_dovecot_user_hash %}{{ _mail_dovecot_user_hash.stdout }}{% else %}{{ user.pass }}{% endif %}:{{ user.uid|default("") }}:{{ user.gid|default("") }}:{{ user.gecos|default("") }}:{{ user.home|default("") }}:{{ user.shell|default("") }}:{{ user.extra|default("") }}'
    owner:  'root'
    group:  '{{ mail_dovecot_group }}'
    mode:   0640
    state:  'present'
  changed_when: false
