---
###############################################################################
# OpenDKIM Configuration
###############################################################################
# OpenDKIM is an open source implementation of the DKIM (Domain Keys Identified
# Mail) sender authentication system proposed by the E-mail Signing Technology
# Group (ESTG) (RFC5617), now standardized by the IETF (RFC6376). It also
# includes implementations of  Vouch By Reference (VBR, RFC5518) proposed
# standard and the experimental Authorized Third Party Signatures protocol
# (ATPS, RFC6541).
#
# Args:
#   mail_postfix_user: string postfix user.
#   mail_opendkim_user: string opendkim user.
#   mail_opendkim_group: string opendkim group.
#
# Reference:
# * http://www.opendkim.org/
# * https://wiki.debian.org/opendkim
# * https://wiki.archlinux.org/title/OpenDKIM
# * https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-dkim-with-postfix-on-debian-wheezy

- name: 'dkim | add postfix user to opendkim group'
  ansible.builtin.user:
    name: '{{ mail_postfix_user }}'
    append: true
    groups:
      - '{{ mail_opendkim_group }}'
    state: 'present'

- name: 'dkim | set pidfile ownership'
  ansible.builtin.file:
    path:  '/run/opendkim/opendkim.pid'
    owner: '{{ mail_opendkim_user }}'
    group: '{{ mail_opendkim_group }}'
    mode:  0644
  failed_when: false # if pidfile does not exist, do not fail.

- ansible.builtin.include_tasks: default.opendkim.yml
- ansible.builtin.include_tasks: opendkim.conf.yml
- ansible.builtin.include_tasks: key_management.yml
