---
###############################################################################
# Validate Configuration Options
###############################################################################
# Validate required options for a working mail server. Additional validation is
# done in subroles as needed after configuration occurs.
#
# Confirm naked domain (exmaple.com) has no direct CNAME records (example.com).
# This will cause mail delivery to fail.
#
# Ensure an MX record is created for the bald domain (example.com) that points
# to the FQDN MX mail name (typically: mail.example.com).
#
# Ensure A record is created for FQDN MX mail name mapping to a public IP.
# Confirm that this public IP is the current public IP for the mail server.
#
# Args:
#   mail_domains: list of strings, domains to host, first domain primary.

- name: 'config | check DNS records'
  ansible.builtin.include_tasks: check_dns.yml
  loop: '{{ mail_domains }}'
  loop_control:
    loop_var: domain
