---
###############################################################################
# Validate Configuration Options
###############################################################################
# Validate required options for a working mail server. Additional validation is
# done in subroles as needed after configuration occurs.
#
# Confirm DMARC records exist and restrict appropriately. See check_dmarc.yml
# for specific DMARC settings.
#
# Args:
#   mail_domains: list of strings, domains to host, first domain primary.

- name: 'dmarc | check DMARC records'
  ansible.builtin.include_tasks: check_dmarc.yml
  loop: '{{ mail_domains }}'
  loop_control:
    loop_var: domain
