---
###############################################################################
# Postfix MTA PostSRS Settings
###############################################################################
# Postfix attempts to be fast, easy to administer, and secure. The outside has
# a definite Sendmail-ish flavor, but the inside is completely different.
#
# Configure postfix settings. When the same parameter is defined multiple
# times, only the last instance is remembered. Otherwise, the order of main.cf
# parameter definitions does not matter.
#
# postconf commands never report changed. postconf does not return any
# information on whether a line was or was not changed via exit codes or
# verbose mode. Force execute a postfix reload after configuration is set.
# Queries for UID/GID do not change system.
#
# To ensure service additions/deletions; master.cf is cleared before modifying,
# so default services are included in this configuration even if unchanged.
#
# postfix must be reloaded to pickup changes in main.cf.
#
# Manage postsrs settings.
#
# Reference:
# * http://www.postfix.org/
# * http://www.postfix.org/postconf.5.html

- name: 'postfix settings postsrs | use postsrs for rewriting sender addresses'
  ansible.builtin.command: 'postconf sender_canonical_maps=tcp:localhost:10001'
  changed_when: false

- name: 'postfix settings postsrs | only re-write envelope, header addresses for senders'
  ansible.builtin.command: 'postconf sender_canonical_classes=envelope_sender,header_sender'
  changed_when: false

- name: 'postfix settings postsrs | use postsrs for rewriting recipient addresses'
  ansible.builtin.command: 'postconf recipient_canonical_maps=tcp:localhost:10002'
  changed_when: false

- name: 'postfix settings postsrs | only re-write envelope, header addresses for recipients'
  ansible.builtin.command: 'postconf recipient_canonical_classes=envelope_recipient,header_recipient'
  changed_when: false
