---
###############################################################################
# OepnDMARC User
###############################################################################

- name: 'user | create opendmarc group'
  ansible.builtin.group:
    name:  'opendmarc'
    gid:   607
    state: 'present'

- name: 'user | create opendmarc user'
  ansible.builtin.user:
    name:            'opendmarc'
    group:           'opendmarc'
    uid:             607
    shell:           '/usr/sbin/nologin'
    home:            '/var/run/opendmarc'
    create_home:     false
    password:        '!'
    password_lock:   true
    update_password: 'always'
    expires:         -1
    system:          true
    state:           'present'
